import type { WeakVerbRule } from "./types";

export const weakVerbs: WeakVerbRule[] = [
  { weak: "helped", strong: ["accelerated", "enabled", "strengthened", "advanced"], category: "collaboration" },
  { weak: "worked on", strong: ["engineered", "delivered", "executed", "owned"], category: "delivery" },
  { weak: "did", strong: ["performed", "executed", "completed", "conducted"], category: "delivery" },
  { weak: "made", strong: ["created", "designed", "produced", "launched"], category: "development" },
  { weak: "used", strong: ["leveraged", "applied", "utilized", "implemented"], category: "analysis" },
  { weak: "assisted", strong: ["supported", "coordinated", "facilitated", "enabled"], category: "collaboration" },
  { weak: "handled", strong: ["managed", "resolved", "coordinated", "processed"], category: "delivery" },
  { weak: "managed", strong: ["directed", "orchestrated", "supervised", "oversaw"], category: "leadership" },
  { weak: "was responsible for", strong: ["owned", "led", "delivered", "administered"], category: "leadership" },
  { weak: "participated in", strong: ["contributed to", "collaborated on", "shaped", "influenced"], category: "collaboration" },
  { weak: "tried", strong: ["piloted", "evaluated", "tested", "validated"], category: "analysis" },
  { weak: "contributed to", strong: ["advanced", "strengthened", "co-developed", "enhanced"], category: "collaboration" },
  { weak: "supported", strong: ["enabled", "sustained", "reinforced", "stabilized"], category: "collaboration" },
  { weak: "maintained", strong: ["optimized", "stabilized", "administered", "sustained"], category: "delivery" },
  { weak: "updated", strong: ["modernized", "refined", "upgraded", "revised"], category: "development" },
  { weak: "fixed", strong: ["resolved", "remediated", "debugged", "restored"], category: "development" },
  { weak: "created", strong: ["designed", "launched", "authored", "produced"], category: "development" },
  { weak: "built", strong: ["architected", "engineered", "developed", "implemented"], category: "development" },
  { weak: "ran", strong: ["operated", "facilitated", "executed", "administered"], category: "delivery" },
  { weak: "led", strong: ["directed", "spearheaded", "guided", "orchestrated"], category: "leadership" },
  { weak: "reviewed", strong: ["audited", "evaluated", "assessed", "validated"], category: "analysis" },
  { weak: "tested", strong: ["validated", "verified", "benchmarked", "quality-assured"], category: "analysis" },
  { weak: "wrote", strong: ["authored", "documented", "drafted", "composed"], category: "communication" },
  { weak: "performed", strong: ["executed", "conducted", "delivered", "completed"], category: "delivery" },
  { weak: "completed", strong: ["delivered", "finalized", "executed", "shipped"], category: "delivery" },
  { weak: "improved", strong: ["optimized", "increased", "reduced", "enhanced"], category: "analysis" },
  { weak: "developed", strong: ["engineered", "programmed", "implemented", "architected"], category: "development" },
  { weak: "implemented", strong: ["deployed", "integrated", "launched", "operationalized"], category: "development" },
  { weak: "organized", strong: ["coordinated", "structured", "orchestrated", "planned"], category: "leadership" },
  { weak: "prepared", strong: ["compiled", "produced", "authored", "assembled"], category: "communication" }
];
